### ISSUE TITLE
Blade BeamDyn model

### ISSUE THREAD

**Issue by FPienkny** [IEAWindTask37/IEA-3.4-130-RWT#2]
Hey, 

I am wondering whether there will be added a BeamDyn model of the blade?

Best regards,
Friedrich

**Comment by ptrbortolotti** [comment]
Dear Friedrich,
we have recently completed the development of a novel toolset to generate BeamDyn input files. You can know more from this journal article https://doi.org/10.1016/j.compstruct.2020.112755 
We have not yet had the time to generate the BeamDyn files for the IEA land-based RWT, but I am happy to add this to the to-do list. Please give me a few days and I can try to get this done. If you are in a rush, you can build the two BeamDyn inputs yourself from the tab BladeStructuralProperties of this xlsx https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/master/xlsx/IEAonshore.xlsx
Regards,
Pietro

**Comment by FPienkny** [comment]
Hello Pietro,

Thank you very much for the fast response. This issue is not so urgent but I will have a look into the files anyway. Thanks again for the helpful tips.

Best regards,
Friedrich

**Comment by ptrbortolotti** [comment]
Hi Friedrich,
this morning I finally found the time to run SONATA (https://doi.org/10.1016/j.compstruct.2020.112755) and generate the BeamDyn files. They are located in the f/BeamDyn branch.
This activity brough to life a few inconsistencies. I solved some, but some still need some attention:
1) The interpolation of the airfoil shapes from the root cylinder to the flatback airfoils is returning "weird" shapes. This has been an issue for a long time and there is no easy solution to this problem
2) As a result of 1), the code is confused about the location of the trailing edge and the TE reinforcement layer is not well placed toward the root
3) The web angle toward the root is suspicious. I believe this is caused by problem 2)
4) The position of the spar caps is not always at max chord wise thickness. I have to cross check the results with the ones from TUM

Once I successfully go through these points, I should also run a comparison against the data from PreComp and TUM. I should be able to get to this in the next days

Thanks for your patience and best regards,
Pietro

**Comment by FPienkny** [comment]
Hey Pietro,

No worries, thank you for the update!

Meanwhile I conducted several simulations without BeamDyn (mostly for the parked turbine) that led to other problems. Right now I am trying to solve these but in case I am not succesful I will probably open another issue discussion soon ;)

Best regards,
Friedrich
